In [ ]:
!pip install transformers
!pip install vaderSentiment
!pip install tqdm

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.4.22)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 6.7 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

In [ ]:
import pandas as pd
import numpy as np
import json
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from tqdm import tqdm

In [ ]:
dataset_news = pd.read_csv("news.csv")

In [ ]:
dataset_news.head()

,id,article_language,title,full_text,author,publish_dttm,modified_dttm,url,tags,content_hash,last_updated
0,2,en,OpenAI CEO urges U.S. to prepare for AI ‘super...,OpenAI Chief Executive Sam Altman said U.S. po...,francisco-rodrigues,2026-04-06 15:47:00,2026-04-06 15:47:00,https://www.coindesk.com/tech/2026/04/06/opena...,{artificial-intelligence},82176300df2e50c4c4a8d17085f8ac4d,2026-04-20 22:54:02.084447
1,3,en,Jamie Dimon says JPMorgan must move faster as ...,JPMorgan (JPM) CEO Jamie Dimon said the bank m...,"helene-braun, ai-boost",2026-04-06 15:41:00,2026-04-06 15:41:00,https://www.coindesk.com/markets/2026/04/06/ja...,"{jpm-coin,tokenization,stablecoins}",5773082e8fd1f224f57929c0dfb2cdcf,2026-04-20 22:54:03.114846
2,577,en,CoinDesk 20 performance update: index falls 3....,CoinDesk Indices presents its daily market upd...,coindesk-indices,2026-03-26 13:18:00,2026-03-26 13:18:00,https://www.coindesk.com/coindesk-indices/2026...,"{coindesk-indices,coindesk-20,charts,prices}",e5f1dda47b8c6fec640e3aa8f97f7f08,2026-04-20 22:57:24.217337
3,6,en,Bitmine's ether treasury hits 4.8 million ETH ...,Bitmine Immersion Technologies (BMNR) said it ...,shaurya-malwa,2026-04-06 13:46:00,2026-04-06 13:46:00,https://www.coindesk.com/markets/2026/04/06/bi...,"{digital-asset-treasury,staking}",f445539c0c97f1654444adff9b6ba01c,2026-04-20 22:54:07.308005
4,578,en,MARA Holdings higher by 10% after selling $1.1...,"MARA Holdings (MARA) sold 15,133 bitcoin for a...","james-van-straten, ai-boost",2026-03-26 12:23:00,2026-03-26 12:23:00,https://www.coindesk.com/markets/2026/03/26/ma...,{bitcoin},05a8131f6ecb0b0dfb265b815339a98b,2026-04-20 22:57:25.293738

In [ ]:
df_text = pd.DataFrame(dataset_news)[['publish_dttm', 'full_text']]

In [ ]:
df_text.head()

          publish_dttm                                          full_text
0  2026-04-06 15:47:00  OpenAI Chief Executive Sam Altman said U.S. po...
1  2026-04-06 15:41:00  JPMorgan (JPM) CEO Jamie Dimon said the bank m...
2  2026-03-26 13:18:00  CoinDesk Indices presents its daily market upd...
3  2026-04-06 13:46:00  Bitmine Immersion Technologies (BMNR) said it ...
4  2026-03-26 12:23:00  MARA Holdings (MARA) sold 15,133 bitcoin for a...

In [ ]:
url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
contains_urls = df_text['full_text'].str.contains(url_pattern, regex=True)

if contains_urls.any():
    print("There is a URL in the text.")
else:
    print("There are no URLs in the text.")

There is a URL in the text.

In [ ]:
df_text['full_text'] = df_text['full_text'].str.replace(url_pattern, '', regex=True)

In [ ]:
url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
contains_urls = df_text['full_text'].str.contains(url_pattern, regex=True)

if contains_urls.any():
    print("There is a URL in the text.")
else:
    print("There are no URLs in the text.")

There are no URLs in the text.

In [ ]:
number_pattern = r'\d+'
contains_numbers = df_text['full_text'].str.contains(number_pattern, regex=True)

if contains_numbers.any():
    print("There are numbers in the text.")
else:
    print("There are no numbers in the text.")

There are numbers in the text.

In [ ]:
df_text['full_text'] = df_text['full_text'].str.replace(r'\d+', '', regex=True)

In [ ]:
number_pattern = r'\d+'
contains_numbers = df_text['full_text'].str.contains(number_pattern, regex=True)

if contains_numbers.any():
    print("There are numbers in the text.")
else:
    print("There are no numbers in the text.")

There are no numbers in the text.

In [ ]:
mention_pattern = r'@\w+'
contains_mentions = df_text['full_text'].str.contains(mention_pattern, regex=True)

if contains_mentions.any():
    print("There are mentions in the text.")
else:
    print("There are no mentions in the text.")

There are mentions in the text.

In [ ]:
df_text['full_text'] = df_text['full_text'].str.replace(mention_pattern, '', regex=True)

In [ ]:
contains_mentions_after = df_text['full_text'].str.contains(mention_pattern, regex=True)
if contains_mentions_after.any():
    print("There are mentions in the text after removal.")
else:
    print("There are no mentions in the text after removal.")

There are no mentions in the text after removal.

In [ ]:
df_text['publish_dttm'] = pd.to_datetime(df_text['publish_dttm'])

print(df_text[:5])

         publish_dttm                                          full_text
0 2026-04-06 15:47:00  OpenAI Chief Executive Sam Altman said U.S. po...
1 2026-04-06 15:41:00  JPMorgan (JPM) CEO Jamie Dimon said the bank m...
2 2026-03-26 13:18:00  CoinDesk Indices presents its daily market upd...
3 2026-04-06 13:46:00  Bitmine Immersion Technologies (BMNR) said it ...
4 2026-03-26 12:23:00  MARA Holdings (MARA) sold , bitcoin for approx...

In [ ]:
analyzer = SentimentIntensityAnalyzer()

df_text['VADER_scores'] = df_text['full_text'].apply(lambda x: analyzer.polarity_scores(x))
df_text['compound'] = df_text['VADER_scores'].apply(lambda d: d['compound'])

In [ ]:
df_text.head()

         publish_dttm                                          full_text  \
0 2026-04-06 15:47:00  OpenAI Chief Executive Sam Altman said U.S. po...
1 2026-04-06 15:41:00  JPMorgan (JPM) CEO Jamie Dimon said the bank m...
2 2026-03-26 13:18:00  CoinDesk Indices presents its daily market upd...
3 2026-04-06 13:46:00  Bitmine Immersion Technologies (BMNR) said it ...
4 2026-03-26 12:23:00  MARA Holdings (MARA) sold , bitcoin for approx...

                                        VADER_scores  compound
0  {'neg': 0.072, 'neu': 0.814, 'pos': 0.114, 'co...    0.9792
1  {'neg': 0.054, 'neu': 0.863, 'pos': 0.083, 'co...    0.9132
2  {'neg': 0.022, 'neu': 0.978, 'pos': 0.0, 'comp...   -0.1326
3  {'neg': 0.018, 'neu': 0.923, 'pos': 0.058, 'co...    0.8294
4  {'neg': 0.032, 'neu': 0.899, 'pos': 0.068, 'co...    0.7713

In [ ]:
def categorize_sentiment(compound_score):
    if compound_score > 0.05:
        return 1
    elif compound_score < -0.05:
        return -1
    else:
        return 0

df_text['VADER_Sentiment_Scores'] = df_text['compound'].apply(categorize_sentiment)

In [ ]:
df_text.head(5)

,publish_dttm,full_text,VADER_scores,compound,VADER_Sentiment_Scores
0,2026-04-06 15:47:00,OpenAI Chief Executive Sam Altman said U.S. po...,"{'neg': 0.072, 'neu': 0.814, 'pos': 0.114, 'co...",0.9792,1
1,2026-04-06 15:41:00,JPMorgan (JPM) CEO Jamie Dimon said the bank m...,"{'neg': 0.054, 'neu': 0.863, 'pos': 0.083, 'co...",0.9132,1
2,2026-03-26 13:18:00,CoinDesk Indices presents its daily market upd...,"{'neg': 0.022, 'neu': 0.978, 'pos': 0.0, 'comp...",-0.1326,-1
3,2026-04-06 13:46:00,Bitmine Immersion Technologies (BMNR) said it ...,"{'neg': 0.018, 'neu': 0.923, 'pos': 0.058, 'co...",0.8294,1
4,2026-03-26 12:23:00,"MARA Holdings (MARA) sold , bitcoin for approx...","{'neg': 0.032, 'neu': 0.899, 'pos': 0.068, 'co...",0.7713,1

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
from tqdm import tqdm
from torch.nn.functional import softmax

def sentim_analyzer(df, tokenizer, model):
    for i in tqdm(df.index):
        try:
            text_content = df.loc[i, 'full_text']
        except:
            return print(' \'text\' column might be missing from dataframe')
        input = tokenizer(text_content, padding=True, truncation=True, return_tensors='pt')
        output = model(**input)
        predictions = softmax(output.logits, dim=-1)
        df.loc[i, 'Positive'] = predictions[0][0].tolist()
        df.loc[i, 'Negative'] = predictions[0][1].tolist()
        df.loc[i, 'Neutral']  = predictions[0][2].tolist()
    return df

# Use the modified function:
df_text = sentim_analyzer(df_text, tokenizer, model)

100%|██████████| 11375/11375 [2:29:34<00:00,  1.27it/s]

In [ ]:
df_text.head(5)

,publish_dttm,full_text,VADER_scores,compound,VADER_Sentiment_Scores,Positive,Negative,Neutral
0,2026-04-06 15:47:00,OpenAI Chief Executive Sam Altman said U.S. po...,"{'neg': 0.072, 'neu': 0.814, 'pos': 0.114, 'co...",0.9792,1,0.174666,0.032600,0.792735
1,2026-04-06 15:41:00,JPMorgan (JPM) CEO Jamie Dimon said the bank m...,"{'neg': 0.054, 'neu': 0.863, 'pos': 0.083, 'co...",0.9132,1,0.119181,0.015326,0.865494
2,2026-03-26 13:18:00,CoinDesk Indices presents its daily market upd...,"{'neg': 0.022, 'neu': 0.978, 'pos': 0.0, 'comp...",-0.1326,-1,0.027403,0.561865,0.410732
3,2026-04-06 13:46:00,Bitmine Immersion Technologies (BMNR) said it ...,"{'neg': 0.018, 'neu': 0.923, 'pos': 0.058, 'co...",0.8294,1,0.250705,0.019062,0.730234
4,2026-03-26 12:23:00,"MARA Holdings (MARA) sold , bitcoin for approx...","{'neg': 0.032, 'neu': 0.899, 'pos': 0.068, 'co...",0.7713,1,0.885461,0.081486,0.033053

In [ ]:
df_text['BERT_Compound_intermediate'] = df_text['Positive'] - df_text['Negative']

df_text['BERT_Compound'] = np.tanh(df_text['BERT_Compound_intermediate'])

In [ ]:
df_text.head(5)

,publish_dttm,full_text,VADER_scores,compound,VADER_Sentiment_Scores,Positive,Negative,Neutral,BERT_Compound_intermediate,BERT_Compound
0,2026-04-06 15:47:00,OpenAI Chief Executive Sam Altman said U.S. po...,"{'neg': 0.072, 'neu': 0.814, 'pos': 0.114, 'co...",0.9792,1,0.174666,0.032600,0.792735,0.142066,0.141118
1,2026-04-06 15:41:00,JPMorgan (JPM) CEO Jamie Dimon said the bank m...,"{'neg': 0.054, 'neu': 0.863, 'pos': 0.083, 'co...",0.9132,1,0.119181,0.015326,0.865494,0.103855,0.103483
2,2026-03-26 13:18:00,CoinDesk Indices presents its daily market upd...,"{'neg': 0.022, 'neu': 0.978, 'pos': 0.0, 'comp...",-0.1326,-1,0.027403,0.561865,0.410732,-0.534462,-0.488784
3,2026-04-06 13:46:00,Bitmine Immersion Technologies (BMNR) said it ...,"{'neg': 0.018, 'neu': 0.923, 'pos': 0.058, 'co...",0.8294,1,0.250705,0.019062,0.730234,0.231643,0.227587
4,2026-03-26 12:23:00,"MARA Holdings (MARA) sold , bitcoin for approx...","{'neg': 0.032, 'neu': 0.899, 'pos': 0.068, 'co...",0.7713,1,0.885461,0.081486,0.033053,0.803974,0.666253

In [ ]:
def categorize_sentiment(compound_score):
    if compound_score > 0.05:
        return 1
    elif compound_score < -0.05:
        return -1
    else:
        return 0

df_text['BERT_Sentiment_Scores'] = df_text['BERT_Compound'].apply(categorize_sentiment)

In [ ]:
df_text.tail(5)

,publish_dttm,full_text,VADER_scores,compound,VADER_Sentiment_Scores,Positive,Negative,Neutral,BERT_Compound_intermediate,BERT_Compound,BERT_Sentiment_Scores
11370,2025-01-02 10:36:00,"Tether's USDT, the world's leading dollar-pegg...","{'neg': 0.051, 'neu': 0.867, 'pos': 0.082, 'co...",0.7612,1,0.007908,0.969232,0.022860,-0.961323,-0.744867,-1
11371,2025-01-02 10:10:00,KuCoin has introduced a feature for merchants ...,"{'neg': 0.022, 'neu': 0.947, 'pos': 0.03, 'com...",0.3612,1,0.200677,0.009394,0.789929,0.191283,0.188983,1
11372,2025-01-02 08:02:00,Crypto majors zoomed higher in the past hours...,"{'neg': 0.028, 'neu': 0.869, 'pos': 0.103, 'co...",0.9890,1,0.944268,0.014745,0.040986,0.929523,0.730371,1
11373,2025-01-02 06:30:00,Traders are no longer chasing upside in Nasdaq...,"{'neg': 0.072, 'neu': 0.874, 'pos': 0.054, 'co...",-0.4926,-1,0.030461,0.948982,0.020557,-0.918521,-0.725197,-1
11374,2025-01-02 06:00:00,Spanish banking giant Banco Bilbao Vizcaya Arg...,"{'neg': 0.008, 'neu': 0.907, 'pos': 0.085, 'co...",0.9916,1,0.474831,0.012363,0.512806,0.462468,0.432093,1

In [ ]:
columns_to_drop = ["full_text", "VADER_scores", "Positive", "Negative", "Neutral", "BERT_Compound_intermediate"]
df_text = df_text.drop(columns=columns_to_drop)

In [ ]:
df_text.head(5)

,publish_dttm,compound,VADER_Sentiment_Scores,BERT_Compound,BERT_Sentiment_Scores
0,2026-04-06 15:47:00,0.9792,1,0.141118,1
1,2026-04-06 15:41:00,0.9132,1,0.103483,1
2,2026-03-26 13:18:00,-0.1326,-1,-0.488784,-1
3,2026-04-06 13:46:00,0.8294,1,0.227587,1
4,2026-03-26 12:23:00,0.7713,1,0.666253,1

In [ ]:
path = "/content/drive/My Drive/MyData/Sentiment_Scores_Dataset.csv"
df_text.to_csv(path, index=False)

'publish_dttm,compound,VADER_Sentiment_Scores,BERT_Compound,BERT_Sentiment_Scores\n2025-10-17 15:23:00,0.8361,1,0.07929322775045734,1\n2025-08-30 13:00:00,0.9911,1,-0.006973291404406426,0\n2025-06-24 19:00:00,0.84,1,0.14660673208642153,1\n2026-04-08 13:14:00,0.1779,1,0.3421540585034841,1\n2025-09-24 16:00:00,0.9888,1,0.05017818910220348,1\n2026-01-12 05:16:00,-0.9713,-1,-0.7316559539289786,-1\n2025-03-01 04:30:00,0.996,1,-0.1438275811218339,-1\n2025-05-15 11:10:00,0.8147,1,0.027230205226223315,0\n2025-12-18 08:05:00,0.9283,1,0.6385720270498899,1\n2026-04-12 14:00:00,-0.9356,-1,-0.39668233153958227,-1\n2026-03-31 16:59:00,-0.0516,-1,0.6619886346570313,1\n2025-06-28 14:33:00,0.9492,1,0.5410178921407728,1\n2025-03-12 11:15:00,0.4178,1,-0.6806536781033987,-1\n2025-08-09 15:42:00,0.8625,1,-0.12306462903583698,-1\n2025-09-08 11:15:00,0.9474,1,-0.3633054901026876,-1\n2025-01-08 19:37:00,0.0284,0,-0.7394243286024453,-1\n2025-07-09 01:29:00,0.9871,1,0.6455840767352411,1\n2025-10-23 09:59:00,0.9712,1,0.6557605639395622,1\n2025-11-13 16:07:00,0.7184,1,-0.7316981943296281,-1\n2026-01-25 16:00:00,0.9988,1,0.021828938347642463,0\n2025-02-03 12:41:00,-0.9781,-1,-0.7465443940691796,-1\n2025-11-24 13:28:00,0.9743,1,-0.6858005794449492,-1\n2025-06-12 13:55:00,-0.802,-1,-0.7090319903913682,-1\n2026-03-04 04:50:00,0.7469,1,-0.6703655446014992,-1\n2025-08-15 06:16:00,0.9411,1,0.6419645397108672,1\n2025-09-04 16:19:00,0.9374,1,0.29808594692731916,1\n2026-01-03 13:30:00,0.9104,1,0.1564041205356224,1\n2025-06-25 13:10:00,0.1779,1,0.23551360351449158,1\n2025-05-14 08:36:00,0.9571,1,-0.29959003735141687,-1\n2025-07-10 03:19:00,0.6124,1,-0.6001504745612788,-1\n2025-03-19 09:00:00,0.9884,1,0.18695354625278718,1\n2025-02-28 07:09:00,0.9716,1,-0.5824153475192146,-1\n2026-03-23 05:04:00,-0.7906,-1,-0.7363066605618266,-1\n2025-11-09 01:00:00,0.9064,1,-0.7317113090358769,-1\n2025-12-17 16:51:00,0.633,1,-0.7418032772103981,-1\n2025-09-30 02:31:00,0.9844,1,0.09079803535937384,1\n2025-07-30 11:25:00,0.9349,1,0.06459147241876467,1\n2025-06-11 18:25:00,0.9921,1,-0.019490403518943926,0\n2025-07-01 21:53:00,0.9264,1,-0.7171900585908314,-1\n2025-12-24 13:41:00,0.8316,1,0.6951364966791043,1\n2025-08-06 01:18:00,0.9967,1,0.05204163800318824,1\n2025-10-28 14:38:00,0.975,1,-0.012177074032120356,0\n2025-05-31 17:16:00,-0.549,-1,0.49834450817715487,1\n2025-11-03 16:21:00,-0.25,-1,-0.675620248678233,-1\n2025-04-07 22:00:00,0.9186,1,0.3302199000086972,1\n2025-06-03 20:46:00,0.3612,1,-0.7232494706088609,-1\n2025-08-01 11:15:00,0.9815,1,-0.7118983413929661,-1\n2025-09-18 05:32:00,0.9786,1,0.52748526735761,1\n2025-03-04 16:21:00,-0.5719,-1,-0.0013883775492574853,0\n2026-03-24 12:36:00,0.1779,1,-0.704923545569186,-1\n2025-03-10 17:30:00,0.7543,1,-0.409555082754345,-1\n2025-02-10 14:11:00,0.1779,1,0.25721228361402076,1\n2025-12-16 17:35:00,0.9435,1,0.03746800685811349,0\n2025-05-15 16:10:00,-0.228,-1,-0.47213603144631106,-1\n2025-02-26 18:31:00,-0.2773,-1,-0.6702099945163882,-1\n2025-05-28 14:25:00,-0.5719,-1,-0.7161109483344458,-1\n2025-05-15 06:55:00,0.9711,1,-0.4432200799801614,-1\n2025-07-23 14:48:00,0.2263,1,0.15738086613333846,1\n2025-08-18 18:36:00,0.966,1,0.45421522504030404,1\n2025-04-24 14:17:00,0.9995,1,0.12851288854376364,1\n2026-04-17 17:50:00,0.9798,1,0.12998965843719282,1\n2025-10-20 14:18:00,0.9887,1,0.17232975300299144,1\n2025-09-11 19:23:00,0.9708,1,0.15519189916853537,1\n2025-03-19 15:05:00,0.9928,1,-0.2729928872877248,-1\n2025-08-12 21:12:00,0.401,1,0.4812775541969157,1\n2025-07-31 13:00:00,0.7244,1,0.2686930913306904,1\n2025-12-30 07:43:00,0.992,1,0.07361719824821265,1\n2025-07-04 15:08:00,-0.8225,-1,-0.5841307087170247,-1\n2025-07-15 09:24:00,0.9885,1,-0.6716725338217778,-1\n2025-09-13 14:00:00,0.9875,1,-0.38063947294145956,-1\n2025-07-07 15:20:00,0.7992,1,0.08053198377518497,1\n2025-03-26 16:03:00,0.9946,1,-0.041001142224490826,0\n2025-03-31 13:52:00,0.8271,1,-0.0358901924513333,0\n2025-10-07 15:45:00,0.796,1,-0.5861344944515126,-1\n2025-05-02 11:53:00,0.959,1,0.6390197012155132,1\n2025-07-08 16:22:00,-0.9757,-1,-0.7094252188491146,-1\n2025-10-31 16:24:00,0.6486,1,0.10517585350293472,1\n2026-03-25 05:26:00,0.6386,1,-0.6611796585432732,-1\n2025-07-10 16:43:00,0.9601,1,0.7281960971021568,1\n2026-03-30 13:00:00,0.9866,1,0.2958996923936168,1\n2026-01-05 15:30:00,0.9274,1,0.14726668768880288,1\n2025-06-11 18:45:00,0.995,1,0.33381828534334246,1\n2026-04-07 15:26:00,-0.9112,-1,-0.43411713755470166,-1\n2025-04-16 15:39:00,0.996,1,-0.6323008617173059,-1\n2026-03-09 15:26:00,0.6908,1,0.7285581088829634,1\n2025-04-21 18:32:00,0.9925,1,0.4965285576978658,1\n2026-01-30 09:48:00,0.9473,1,-0.7277712637982889,-1\n2025-07-21 21:08:00,0.8658,1,0.10246621704786832,1\n2025-11-18 16:38:00,0.8699,1,0.015463639368436033,0\n2025-11-25 19:00:00,0.836,1,0.7297178290293023,1\n2025-01-16 22:23:00,0.3883,1,-0.4981339038021869,-1\n2025-12-03 15:37:00,0.5666,1,0.30174293403807756,1\n2025-05-28 13:00:00,-0.802,-1,-0.6934409686681775,-1\n2025-06-27 16:17:00,0.8127,1,0.12090995185430989,1\n2025-12-03 14:53:00,0.9814,1,0.42554763576024157,1\n2025-04-21 20:35:00,-0.3788,-1,-0.7302681152601811,-1\n2025-03-05 15:39:00,0.9583,1,0.5058508575680817,1\n2025-04-02 15:00:00,0.9995,1,0.17276314606293322,1\n2026-01-07 18:21:00,0.9864,1,0.23248795962720123,1\n2026-02-05 23:39:00,0.0129,0,0.23310748677712467,1\n2025-12-17 17:14:00,-0.4215,-1,-0.7441081621455866,-1\n2026-04-09 09:29:00,0.8347,1,0.1520611173175959,1\n2026-02-26 20:33:00,0.9961,1,0.0057961701448408925,0\n2025-01-22 08:49:00,0.9371,1,-0.1552684969358953,-1\n2025-04-30 06:15:00,0.9633,1,0.1988836394452331,1\n2025-08-22 09:28:00,0.242,1,-0.6713343523169433,-1\n2026-01-20 15:10:00,0.9862,1,0.06648784373538813,1\n2025-01-28 04:56:00,0.969,1,-0.024199081830209877,0\n2025-07-14 11:15:00,0.9649,1,0.5777943892839883,1\n2025-11-17 17:11:00,0.967,1,0.04969525488274161,0\n2025-10-19 13:42:00,0.0516,1,-0.1453021696746106,-1\n2025-03-25 06:30:00,0.9932,1,0.7053246450743008,1\n2026-01-29 15:53:00,0.9961,1,0.058512938985964484,1\n2025-09-03 03:05:00,0.1531,1,-0.5718660606324037,-1\n2025-05-15 14:58:00,0.4005,1,-0.6672505978259126,-1\n2025-06-11 14:44:00,0.9337,1,0.2047747957907464,1\n2025-10-06 06:41:00,0.8887,1,-0.7203025474544098,-1\n2025-11-26 07:06:00,-0.2534,-1,0.044103335831247974,0\n2025-04-30 12:17:00,0.975,1,0.12518659754243527,1\n2026-03-05 10:42:00,0.9876,1,0.07319447654485242,1\n2026-03-30 18:15:00,0.9456,1,0.3312695329372947,1\n2025-05-29 14:45:00,0.9497,1,0.7278388184197288,1\n2025-12-22 13:59:00,0.9059,1,0.3070292779248773,1\n2025-03-27 18:48:00,0.9931,1,0.1466429535360777,1\n2025-03-05 12:15:00,-0.1825,-1,-0.7221687021086881,-1\n2025-06-27 20:54:00,0.9958,1,0.09829587634706628,1\n2026-04-15 10:47:00,0.6486,1,-0.7179133827344936,-1\n2025-05-08 07:59:00,0.5267,1,-0.09275898526326151,-1\n2026-04-14 08:49:00,-0.7354,-1,-0.26593032030494335,-1\n2025-07-09 10:32:00,0.34,1,-0.07057305467119439,-1\n2025-12-11 16:24:00,0.7992,1,-0.728444929681322,-1\n2026-01-30 14:00:00,0.7184,1,0.08946279657704662,1\n2025-02-28 06:54:00,-0.9453,-1,-0.7432602337421319,-1\n2025-07-09 13:53:00,0.9274,1,0.5091429934761618,1\n2025-12-05 15:23:00,0.9993,1,-0.741284895716464,-1\n2025-01-22 14:00:00,0.9831,1,0.5707819859863961,1\n2026-03-09 08:44:00,0.8935,1,-0.544767177402881,-1\n2025-06-05 18:26:00,0.1298,1,-0.7298489834145189,-1\n2025-12-21 21:25:00,-0.4224,-1,-0.20708626991666168,-1\n2025-08-04 08:30:00,0.8979,1,-0.7207852473482893,-1\n2025-06-04 09:43:00,0.836,1,0.7113627691956337,1\n2025-08-13 09:00:00,0.9755,1,0.20781525264090786,1\n2025-11-19 23:43:00,0.875,1,0.2033702399022285,1\n2025-10-15 14:15:00,0.9081,1,0.4054880616658249,1\n2025-07-18 06:29:00,0.994,1,0.4447548397396141,1\n2025-03-11 13:00:00,-0.3089,-1,-0.6443559377864342,-1\n2025-07-14 08:12:00,0.3182,1,-0.360326167778579,-1\n2025-07-04 10:06:00,0.9782,1,0.5828445473342506,1\n2025-03-13 17:48:00,0.9921,1,0.32566898849575276,1\n2025-12-16 06:38:00,0.9942,1,0.14813040868065425,1\n2025-09-16 12:56:00,0.627,1,-0.6891905268428273,-1\n2026-03-03 08:25:00,0.9081,1,0.04660571402791459,0\n2025-04-02 09:03:00,-0.7003,-1,-0.6748274995056814,-1\n2025-03-24 19:05:00,0.985,1,0.6086108335101682,1\n2025-07-30 15:53:00,0.3447,1,-0.7449794155196163,-1\n2025-06-24 19:19:00,0.9723,1,0.7272379366103456,1\n2025-06-17 13:35:00,-0.9183,-1,-0.739241212469999,-1\n2025-10-03 16:27:00,0.8126,1,0.7273156407961282,1\n2025-07-28 12:15:00,0.836,1,0.7257896121955991,1\n2025-09-06 14:00:00,0.9962,1,0.05582758286298568,1\n2025-06-11 12:42:00,0.9531,1,-0.6868070309262719,-1\n2025-12-11 07:57:00,0.9872,1,0.42176377951973815,1\n2025-10-14 16:10:00,0.7013,1,-0.6953842235837642,-1\n2025-07-15 01:45:00,0.9976,1,0.7303448732687347,1\n2025-02-11 15:00:00,0.9918,1,0.17284132792132892,1\n2025-09-23 00:04:00,0.984,1,0.15971173103682207,1\n2025-11-21 13:59:00,0.9709,1,0.6699517400252587,1\n2025-07-22 15:38:00,0.802,1,-0.7357832289790844,-1\n2025-08-29 05:52:00,0.9821,1,0.48222714787828713,1\n2025-12-02 09:11:00,-0.5409,-1,-0.09330914579494518,-1\n2026-03-29 13:00:00,0.9892,1,-0.05863176528919642,-1\n2025-12-01 13:37:00,-0.8718,-1,-0.7421945635353507,-1\n2025-06-12 12:00:00,0.9152,1,0.04469295759651923,0\n2026-03-10 04:42:00,-0.566,-1,-0.7101148693381932,-1\n2026-03-24 16:05:00,0.8431,1,0.04455168029378973,0\n2025-07-11 14:00:00,0.9833,1,0.698195589754668,1\n2025-04-17 11:35:00,0.548,1,-0.2870336952943637,-1\n2025-10-08 12:34:00,0.6808,1,-0.7388967044484077,-1\n2025-02-13 15:06:00,0.6486,1,0.01787139910711143,0\n2025-04-10 14:55:00,0.9571,1,0.05401704004265746,1\n2025-05-12 12:14:00,0.8316,1,0.1655810153991353,1\n2025-06-03 07:51:00,0.9501,1,0.3565585339101358,1\n2025-03-17 13:18:00,0.9324,1,-0.7283704677111387,-1\n2025-12-03 17:23:00,0.6894,1,0.6941553502493479,1\n2025-03-05 05:18:00,0.4404,1,-0.02475734694183078,0\n2025-05-21 13:00:00,0.8977,1,0.153378303107103,1\n2025-06-20 17:53:00,0.975,1,0.1328938453278537,1\n2026-01-22 16:13:00,0.8481,1,-0.7441924956559519,-1\n2025-03-13 12:11:00,-0.2023,-1,-0.7409585429930671,-1\n2025-12-03 22:32:00,-0.9612,-1,-0.4408610512766881,-1\n2025-01-20 15:45:00,0.8225,1,0.06881326214405961,1\n2026-02-18 06:54:00,0.9217,1,-0.40721278490870894,-1\n2025-07-16 06:22:00,0.984,1,0.20316848265922643,1\n2025-05-07 13:19:00,0.9991,1,0.4529445111509184,1\n2026-01-21 02:01:00,-0.9915,-1,-0.6984183380029478,-1\n2025-08-21 17:31:00,0.9934,1,0.7156199722589134,1\n2025-05-19 15:53:00,-0.7387,-1,-0.2874213050788574,-1\n2025-09-04 12:04:00,0.3071,1,0.10448339796723999,1\n2025-03-29 17:14:00,-0.8402,-1,-0.5759069939782101,-1\n2025-06-25 11:48:00,0.7231,1,0.258825740081168,1\n2025-02-26 12:15:00,0.9492,1,-0.5180637903495008,-1\n2026-03-24 20:48:00,0.0274,0,-0.7274159100151008,-1\n2025-04-02 15:57:00,0.9945,1,0.06613564385985234,1\n2026-03-18 20:31:00,0.9976,1,-0.20779876720635884,-1\n2025-03-06 16:56:00,0.978,1,0.16732670791203993,1\n2025-06-27 19:20:00,0.9962,1,0.18742804487030287,1\n2025-06-29 21:52:00,0.3214,1,0.6913522343481129,1\n2026-04-01 10:05:00,0.2732,1,-0.7350602551914227,-1\n2025-08-13 08:52:00,0.4019,1,-0.23106164910452195,-1\n2025-03-31 11:45:00,0.705,1,-0.6215874834583719,-1\n2025-05-29 10:50:00,-0.4215,-1,-0.12395285195589567,-1\n2026-04-20 14:31:00,0.926,1,-0.5844937516081642,-1\n2025-07-21 14:11:00,0.914,1,0.18665524299686176,1\n2026-01-18 16:07:00,0.9975,1,-0.2771888716110123,-1\n2025-07-14 09:00:00,0.9041,1,0.4602671418786881,1\n2025-11-04 12:15:00,0.56,1,-0.7433347539597013,-1\n2025-08-14 20:34:00,0.9539,1,-0.47196042396409044,-1\n2025-10-24 13:25:00,-0.3202,-1,0.2732241010718943,1\n2026-01-29 10:12:00,0.7964,1,0.3446565521600757,1\n2025-02-28 04:04:00,-0.9062,-1,-0.7262158881738331,-1\n2026-03-03 19:44:00,0.9983,1,0.01481485373077586,0\n2025-10-03 09:46:00,0.8847,1,0.7010351279668399,1\n2025-06-18 12:07:00,0.8555,1,-0.33007440093494356,-1\n2025-07-21 01:25:00,0.9878,1,0.3527793095032037,1\n2025-05-05 06:39:00,0.9509,1,0.2288008857667304,1\n2025-09-02 07:40:00,-0.7371,-1,-0.6537853824944557,-1\n2026-02-20 06:43:00,-0.9412,-1,-0.47233268876516776,-1\n2025-04-08 12:00:00,0.907,1,0.18086992340315272,1\n2025-09-22 12:36:00,0.7964,1,0.72259267686768,1\n2025-08-08 14:06:00,0.7906,1,0.26495114138125325,1\n2025-03-24 15:03:00,0.9961,1,0.006364546458615446,0\n2025-10-29 10:25:00,0.9809,1,-0.016979366225008615,0\n2025-06-18 20:21:00,0.9733,1,0.13860830722403453,1\n2025-08-06 12:35:00,0.875,1,0.04924078536731181,0\n2025-04-24 11:01:00,0.9451,1,0.23351634053876597,1\n2026-02-18 19:07:00,0.4933,1,0.2500839974445113,1\n2025-05-26 06:26:00,0.8519,1,0.7126239501055628,1\n2026-01-14 00:19:00,0.2794,1,-0.690204294017348,-1\n2025-12-09 13:48:00,0.9245,1,0.641284613168284,1\n2025-08-14 13:00:00,0.9869,1,0.09603894863016968,1\n2025-12-15 02:28:00,-0.9306,-1,-0.44837064311752195,-1\n2025-12-02 16:01:00,0.9061,1,0.6464475114453251,1\n2025-01-13 05:16:00,0.9677,1,0.1177401309235061,1\n2026-02-06 03:27:00,-0.9674,-1,-0.44260683214004887,-1\n2025-10-13 04:26:00,-0.8705,-1,-0.6653988230788114,-1\n2025-02-25 12:30:00,0.9649,1,0.3031765062065229,1\n2025-07-22 07:18:00,0.9826,1,0.6747780454529633,1\n2026-03-23 16:12:00,0.9881,1,0.0711772285730982,1\n2025-02-04 05:46:00,0.3818,1,-0.7430804665342265,-1\n2025-05-30 02:16:00,0.9962,1,-0.0014868479441249804,0\n2025-10-09 19:06:00,-0.4939,-1,-0.7441425607872564,-1\n2025-07-07 17:51:00,0.7845,1,0.2411229922856949,1\n2026-01-08 20:11:00,0.8493,1,0.681815069204586,1\n2025-06-06 18:23:00,0.9172,1,0.7054509219431653,1\n2025-02-05 23:11:00,-0.9588,-1,-0.30912325772079124,-1\n2025-03-10 06:01:00,0.9619,1,0.18049992914338506,1\n2025-06-11 16:00:00,0.2707,1,0.12980004320628682,1\n2026-01-08 14:00:00,0.9118,1,0.05876525588082319,1\n2025-07-11 10:42:00,-0.1547,-1,-0.4660702842175209,-1\n2025-07-30 16:40:00,0.9616,1,0.7203594026571866,1\n2025-12-06 18:03:00,0.7506,1,0.1544108122410338,1\n2025-05-16 16:36:00,0.97,1,0.5599281576011007,1\n2025-09-23 20:55:00,-0.0,0,0.09563226132284469,1\n2025-07-15 18:31:00,0.9996,1,0.1070997101188871,1\n2025-04-28 15:53:00,-0.559,-1,-0.4509541627193111,-1\n2025-06-27 14:52:00,0.9661,1,0.7109093037823336,1\n2025-01-09 06:18:00,0.9735,1,0.023094843844842672,0\n2026-02-19 16:00:00,0.9319,1,0.07718868402328699,1\n2025-06-12 14:00:00,0.9786,1,0.20170353367537752,1\n2025-10-13 05:29:00,0.8834,1,0.6854192277445578,1\n2025-10-27 04:48:00,0.296,1,0.7296487438057851,1\n2025-08-14 20:23:00,-0.8522,-1,-0.5520495178696484,-1\n2025-01-08 08:58:00,0.9922,1,0.7189665717441779,1\n2026-03-31 14:41:00,0.9274,1,0.7258692955609589,1\n2025-09-10 13:24:00,0.6249,1,-0.7015021383958798,-1\n2025-06-12 14:49:00,0.9758,1,0.5622023527274979,1\n2025-11-08 15:00:00,0.988,1,-0.35049601667038527,-1\n2025-09-12 11:37:00,0.6161,1,-0.7024574509902916,-1\n2025-08-19 14:00:00,0.8718,1,0.19966529566520075,1\n2025-01-30 20:52:00,0.8957,1,0.6464920521130559,1\n2025-04-09 18:46:00,-0.1316,-1,0.4866758111143203,1\n2025-09-26 18:45:00,0.9703,1,0.20779256241466004,1\n2025-03-06 16:55:00,0.9583,1,-0.09705415773375711,-1\n2025-04-23 17:30:00,0.5888,1,-0.5700387134684953,-1\n2025-04-30 18:38:00,0.631,1,0.08919498738643307,1\n2025-05-14 15:00:00,0.9887,1,0.22427880040335274,1\n2025-01-29 16:52:00,-0.9594,-1,-0.6529301066452619,-1\n2025-12-18 15:00:00,0.9994,1,0.05083561403219588,1\n2025-08-03 12:15:00,0.9032,1,0.4192300083605993,1\n2025-03-28 11:07:00,0.9432,1,0.6143557100740971,1\n2025-05-05 19:47:00,0.9383,1,-0.24624630547225876,-1\n2026-04-02 13:57:00,0.7986,1,-0.6492596022844536,-1\n2025-11-03 13:57:00,0.9345,1,0.4993973113289583,1\n2025-12-03 12:15:00,0.9834,1,0.6411475574183825,1\n2025-11-19 12:15:00,0.9896,1,0.09513393554408268,1\n2025-03-28 14:17:00,0.91,1,0.05519522489917714,1\n2026-04-03 00:28:00,-0.6124,-1,-0.3820471850565174,-1\n2026-01-09 16:45:00,0.4754,1,-0.672766880605381,-1\n2025-10-13 19:23:00,0.9343,1,0.20649217596350491,1\n2025-02-04 13:55:00,0.8126,1,-0.005730072651860714,0\n2025-04-02 12:16:00,0.9509,1,0.7193617931993501,1\n2025-07-28 13:36:00,0.9859,1,0.5159198741444364,1\n2025-03-05 18:16:00,-0.9954,-1,-0.3734379774194282,-1\n2025-09-22 12:18:00,0.296,1,-0.7286764657243776,-1\n2025-07-11 12:38:00,0.9712,1,0.5713837308173528,1\n2025-10-07 05:01:00,0.6609,1,0.14656532121168106,1\n2026-02-04 12:16:00,0.872,1,-0.729082266330926,-1\n2026-03-06 13:08:00,0.7717,1,0.08630413483570365,1\n2025-11-20 06:45:00,0.9483,1,0.16071121337393376,1\n2025-06-17 06:48:00,0.9186,1,0.7073217437735759,1\n2026-03-18 11:57:00,0.9206,1,-0.39997424675696475,-1\n2025-02-13 16:00:00,0.9903,1,-0.022321405129962665,0\n2026-02-03 13:22:00,0.9636,1,-0.712531281669672,-1\n2025-08-30 09:45:00,0.7184,1,-0.17999674866196316,-1\n2025-06-23 14:15:00,0.9997,1,0.24060400233061296,1\n2026-03-02 07:12:00,-0.9485,-1,-0.7370015269894147,-1\n2026-03-20 11:41:00,0.9757,1,-0.5181758850420923,-1\n2025-10-17 07:23:00,0.767,1,-0.7381549514851156,-1\n2025-08-06 15:47:00,0.8516,1,0.1848432826312725,1\n2025-04-09 09:40:00,-0.9575,-1,-0.7174478285654153,-1\n2025-03-01 02:05:00,-0.5346,-1,-0.3386174771083295,-1\n2025-10-24 13:00:00,0.9995,1,0.5199064121245517,1\n2025-05-19 16:56:00,0.9992,1,-0.0034496349350701446,0\n2025-07-29 17:31:00,0.7358,1,0.09835045181077962,1\n2026-03-30 21:37:00,0.8126,1,-0.1732812302110711,-1\n2025-12-27 15:00:00,0.9814,1,0.03303338039842507,0\n2025-05-31 17:20:00,0.9022,1,-0.2737302731013272,-1\n2025-06-05 15:02:00,-0.2272,-1,-0.6779867502563286,-1\n2025-05-09 14:06:00,0.9782,1,-0.3691184766316446,-1\n2026-03-20 19:27:00,0.9819,1,0.333369411058654,1\n2025-06-16 12:08:00,0.9062,1,0.22940713525706724,1\n2025-05-16 14:49:00,0.9869,1,0.41032860814157635,1\n2025-09-12 14:36:00,0.9794,1,0.7286531798194078,1\n2025-03-13 20:18:00,0.9847,1,0.5804678105105583,1\n2025-05-02 14:34:00,0.9963,1,0.7246421874699313,1\n2026-03-03 13:19:00,0.9485,1,0.5837023153098406,1\n2025-07-18 13:19:00,0.6187,1,0.7315034501992209,1\n2025-08-29 07:00:00,0.597,1,-0.6910481963488356,-1\n2025-09-10 18:22:00,0.9168,1,0.5826532782066116,1\n2025-10-28 11:39:00,0.9442,1,0.7326533559398916,1\n2025-10-29 08:44:00,0.9933,1,0.4265979191124901,1\n2025-05-20 19:38:00,0.9578,1,0.14534992116589032,1\n2025-02-10 09:46:00,0.9153,1,0.6214524713052122,1\n2025-06-11 02:43:00,0.8176,1,0.3111190535459569,1\n2025-05-13 07:18:00,-0.6705,-1,-0.05171660442930715,-1\n2025-07-28 16:50:00,0.8934,1,-0.7185661182181445,-1\n2025-12-19 11:55:00,0.7845,1,0.6425543503997722,1\n2025-07-30 09:36:00,0.985,1,0.7006883985335521,1\n2025-07-15 10:00:00,0.9795,1,0.37612153149131305,1\n2025-05-02 12:46:00,0.9331,1,0.18161910112604593,1\n2025-07-22 05:34:00,0.9909,1,0.7245811300004751,1\n2025-11-28 17:24:00,0.9666,1,0.589883771315322,1\n2025-11-18 18:15:00,-0.9318,-1,-0.7079818707653065,-1\n2025-03-04 17:29:00,0.7096,1,-0.07446859236659233,-1\n2025-12-02 16:11:00,0.6124,1,0.6611458775469603,1\n2026-02-02 21:02:00,0.9957,1,0.052297842261836425,1\n2025-12-18 14:00:00,0.999,1,0.05888208696357799,1\n2026-01-13 08:00:00,0.9014,1,0.36931861087046586,1\n2025-11-26 16:22:00,0.9954,1,-0.6999837637922707,-1\n2025-02-03 08:18:00,0.9659,1,-0.7137239009548547,-1\n2025-03-07 18:18:00,0.9881,1,0.37539396946897385,1\n2026-04-12 11:49:00,0.9753,1,-0.6654776053058516,-1\n2025-05-01 19:47:00,0.8402,1,0.08286208370753383,1\n2025-09-24 09:04:00,0.9233,1,-0.730797519791282,-1\n2025-06-28 17:29:00,0.9507,1,-0.7143692027772856,-1\n2025-05-28 08:06:00,0.9463,1,0.03673331942214245,0\n2025-11-04 19:06:00,0.9591,1,-0.40720147645629096,-1\n2025-10-20 16:47:00,0.9997,1,0.08072002793489046,1\n2025-03-04 09:00:00,0.9831,1,0.6807011113283172,1\n2025-02-03 12:00:00,-0.7727,-1,-0.3370270549639903,-1\n2026-03-19 10:30:00,0.31,1,-0.12980385406310607,-1\n2025-10-02 13:58:00,0.9831,1,0.657406890983686,1\n2025-07-07 10:39:00,-0.5617,-1,0.0017610770139334367,0\n2026-03-21 12:00:00,0.0258,0,-0.6857014093324069,-1\n2025-12-03 05:52:00,0.9402,1,-0.7216714745745292,-1\n2025-04-21 15:27:00,0.999,1,0.12793660642062168,1\n2026-02-11 17:42:00,0.995,1,-0.5115037967002092,-1\n2026-02-22 18:00:00,0.9997,1,0.2038472933125624,1\n2026-03-14 14:00:00,0.9898,1,-0.03171376222447576,0\n2025-02-18 10:23:00,-0.9355,-1,-0.7312314753383967,-1\n2026-02-05 06:12:0

In [ ]:
df_text.to_csv('Sentiment_Scores_Dataset.csv', index=False)

In [ ]:
df_text

,publish_dttm,compound,VADER_Sentiment_Scores,BERT_Compound,BERT_Sentiment_Scores
0,2026-04-06 15:47:00,0.9792,1,0.141118,1
1,2026-04-06 15:41:00,0.9132,1,0.103483,1
2,2026-03-26 13:18:00,-0.1326,-1,-0.488784,-1
3,2026-04-06 13:46:00,0.8294,1,0.227587,1
4,2026-03-26 12:23:00,0.7713,1,0.666253,1
...,...,...,...,...,...
11370,2025-01-02 10:36:00,0.7612,1,-0.744867,-1
11371,2025-01-02 10:10:00,0.3612,1,0.188983,1
11372,2025-01-02 08:02:00,0.9890,1,0.730371,1
11373,2025-01-02 06:30:00,-0.4926,-1,-0.725197,-1
11374,2025-01-02 06:00:00,0.9916,1,0.432093,1

In [ ]:
dataset_bitcointalk

,id,article_language,title,full_text,author,publish_dttm,modified_dttm,url,tags,content_hash,last_updated
0,2,en,OpenAI CEO urges U.S. to prepare for AI ‘super...,OpenAI Chief Executive Sam Altman said U.S. po...,francisco-rodrigues,2026-04-06 15:47:00,2026-04-06 15:47:00,https://www.coindesk.com/tech/2026/04/06/opena...,{artificial-intelligence},82176300df2e50c4c4a8d17085f8ac4d,2026-04-20 22:54:02.084447
1,3,en,Jamie Dimon says JPMorgan must move faster as ...,JPMorgan (JPM) CEO Jamie Dimon said the bank m...,"helene-braun, ai-boost",2026-04-06 15:41:00,2026-04-06 15:41:00,https://www.coindesk.com/markets/2026/04/06/ja...,"{jpm-coin,tokenization,stablecoins}",5773082e8fd1f224f57929c0dfb2cdcf,2026-04-20 22:54:03.114846
2,577,en,CoinDesk 20 performance update: index falls 3....,CoinDesk Indices presents its daily market upd...,coindesk-indices,2026-03-26 13:18:00,2026-03-26 13:18:00,https://www.coindesk.com/coindesk-indices/2026...,"{coindesk-indices,coindesk-20,charts,prices}",e5f1dda47b8c6fec640e3aa8f97f7f08,2026-04-20 22:57:24.217337
3,6,en,Bitmine's ether treasury hits 4.8 million ETH ...,Bitmine Immersion Technologies (BMNR) said it ...,shaurya-malwa,2026-04-06 13:46:00,2026-04-06 13:46:00,https://www.coindesk.com/markets/2026/04/06/bi...,"{digital-asset-treasury,staking}",f445539c0c97f1654444adff9b6ba01c,2026-04-20 22:54:07.308005
4,578,en,MARA Holdings higher by 10% after selling $1.1...,"MARA Holdings (MARA) sold 15,133 bitcoin for a...","james-van-straten, ai-boost",2026-03-26 12:23:00,2026-03-26 12:23:00,https://www.coindesk.com/markets/2026/03/26/ma...,{bitcoin},05a8131f6ecb0b0dfb265b815339a98b,2026-04-20 22:57:25.293738
...,...,...,...,...,...,...,...,...,...,...,...
11370,13217,en,Tether's Market Value Sees Sharpest Decline Si...,"Tether's USDT, the world's leading dollar-pegg...",omkar-godbole,2025-01-02 10:36:00,2025-01-02 10:36:00,https://www.coindesk.com/markets/2025/01/02/te...,"{tether,usdt,stablecoins,markets,bitcoin}",086bac870c390c651b71e84ef44ec125,2026-04-21 20:07:19.263504
11371,13218,en,KuCoin Enables Crypto Point-of-Sale Payments b...,KuCoin has introduced a feature for merchants ...,helene-braun,2025-01-02 10:10:00,2025-01-02 10:23:00,https://www.coindesk.com/business/2025/01/02/k...,"{point-of-sale,payments,kucoin,crypto-exchanges}",68f6170b318cdb9dc5929eaa1dfa80c9,2026-04-21 20:07:21.611766
11372,13219,en,XRP Rockets 11% as Bitcoin Starts New Year Wit...,Crypto majors zoomed higher in the past 24 hou...,shaurya-malwa,2025-01-02 08:02:00,2025-01-02 08:02:00,https://www.coindesk.com/markets/2025/01/02/xr...,"{xrp,bitcoin,markets}",45b14fb116b876f1eb344445012f0557,2026-04-21 20:07:23.474913
11373,13220,en,MicroStrategy's Bullish Call Skew Disappears i...,Traders are no longer chasing upside in Nasdaq...,omkar-godbole,2025-01-02 06:30:00,2025-01-02 08:48:00,https://www.coindesk.com/markets/2025/01/02/bi...,"{bitcoin,microstrategy,mstr,options}",6a64d7d7705430e050a0a1a382ba8f00,2026-04-21 20:07:25.411624
11374,13221,en,Garanti BBVA Kripto Provides Crypto Trading Se...,Spanish banking giant Banco Bilbao Vizcaya Arg...,tom-carreras,2025-01-02 06:00:00,2025-01-14 14:58:00,https://www.coindesk.com/business/2025/01/02/g...,NaN,4b2f48f9c7484da88869780223f72d07,2026-04-21 20:07:27.439009

In [ ]:
len(df_bitcointalk) * 0.05

568.75